### ISSUE TITLE
Higher Order Component doesn't work in conjunction with other HOCs

### ISSUE THREAD

**Issue by mr-14** [RusinovAnton/react-scrollreveal#1]
I tried using withScrollReveal and withRouter in the following ways but none of them worked. And what I mean by not working is that react-router doesn't seem to be receiving state changes when it should. I'm suspecting that withScrollReveal is not propagating props / state change to its wrapped component?

1. Wrapping withScrollReveal inside withRouter:
```
export default withRouter(withScrollReveal([
  {
    selector: '.feature',
    options: {
      reset: false,
      duration: 1000,
      mobile: false
    }
  }
])(Home))
```
2. Wrapping withRouter inside withScrollReveal:
```
export default withScrollReveal([
  {
    selector: '.feature',
    options: {
      reset: false,
      duration: 1000,
      mobile: false
    }
  }
])(withRouter(Home))
```
Any help?

**Comment by RusinovAnton** [comment]
Sorry it took too long to respond, I were moving into another city.  
Anyway, I've created this [CodeSandbox](https://codesandbox.io/s/xll4zp88w4) sample to reproduce your bug and it seems like its working for me, you can see props that were passed into both components in your console.  
Please lmk if I missed something.

**Comment by RusinovAnton** [comment]
@mr-14 shame on me, I've just found huge typo and fixed it. You could update to `1.0.3` and try it.
